'use server'

import { getActionContext } from '@/lib/auth-action'
import { createAdminClient } from '@/utils/supabase/admin'
import { revalidatePath } from 'next/cache'
import { logActivity } from '@/lib/activity-log'

function termDates(yearName: string, term: 'T1' | 'T2' | 'T3') {
    const [startYear, endYear] = yearName.split('-').map(Number)
    if (term === 'T1') return { start: `${startYear}-10-01`, end: `${startYear}-12-31` }
    if (term === 'T2') return { start: `${endYear}-01-05`,   end: `${endYear}-03-31`   }
    return                    { start: `${endYear}-04-06`,   end: `${endYear}-06-30`   }
}

// ─── Academic Years ────────────────────────────────────────────────────────────

export async function createAcademicYear(name: string) {
    const ctx = await getActionContext()
    if (!ctx) return { error: 'Non authentifié' }
    const { schoolId } = ctx
    const db = createAdminClient()

    if (!/^\d{4}-\d{4}$/.test(name)) {
        return { error: 'Format invalide — utilisez AAAA-AAAA (ex: 2025-2026)' }
    }

    const [start, end] = name.split('-').map(Number)
    if (end !== start + 1) {
        return { error: 'Les deux années doivent être consécutives (ex: 2025-2026)' }
    }

    const { data: existing } = await db
        .from('academic_years')
        .select('id')
        .eq('school_id', schoolId)
        .eq('name', name)
        .limit(1)

    if (existing && existing.length > 0) {
        return { error: `L'année scolaire ${name} existe déjà` }
    }

    const newYearId = crypto.randomUUID()

    const { error: yearError } = await db
        .from('academic_years')
        .insert({
            id:         newYearId,
            school_id:  schoolId,
            name:       name,
            start_date: `${start}-10-01`,
            end_date:   `${end}-06-30`,
            is_current: false,
        })

    if (yearError) {
        return { error: yearError?.message ?? 'Erreur création année' }
    }

    // Resiliency: check if a trigger already seeded the terms
    const { data: autogenerated } = await db
        .from('terms')
        .select('id')
        .eq('academic_year_id', newYearId)
        .limit(1)

    if (autogenerated && autogenerated.length > 0) {
        revalidatePath('/admin/terms')
        return { success: true }
    }

    const LABELS = {
        T1: { fr: 'Premier Trimestre',   ar: 'الفصل الأول'   },
        T2: { fr: 'Deuxième Trimestre',  ar: 'الفصل الثاني'  },
        T3: { fr: 'Troisième Trimestre', ar: 'الفصل الثالث'  },
    }

    const terms = (['T1', 'T2', 'T3'] as const).map(termName => {
        const dates = termDates(name, termName)
        const row = {
            school_id:         schoolId,
            academic_year_id: newYearId,
            name:              termName,
            label_fr:          LABELS[termName].fr,
            label_ar:          LABELS[termName].ar,
            start_date:        dates.start,
            end_date:          dates.end,
            is_current:        false,
        }
        return row satisfies {
            school_id: string
            academic_year_id: string
            name: 'T1' | 'T2' | 'T3'
            label_fr: string
            label_ar: string
            start_date: string
            end_date: string
            is_current: boolean
        }
    })

    const { error: termsError } = await db.from('terms').insert(terms)
    if (termsError) return { error: termsError.message }

    logActivity({ actorId: ctx.userId, schoolId, action: 'create_academic_year', entityType: 'academic_year', entityId: newYearId, details: `Année scolaire créée: ${name}` })
    revalidatePath('/admin/terms')
    return { success: true }
}

export async function setCurrentAcademicYear(yearId: string) {
    const ctx = await getActionContext()
    if (!ctx) return { error: 'Non authentifié' }
    const { schoolId } = ctx
    const db = createAdminClient()

    await db.from('academic_years').update({ is_current: false }).eq('school_id', schoolId)

    const { error } = await db
        .from('academic_years')
        .update({ is_current: true })
        .eq('id', yearId)
        .eq('school_id', schoolId)

    if (error) return { error: error.message }

    logActivity({ actorId: ctx.userId, schoolId, action: 'set_current_year', entityType: 'academic_year', entityId: yearId, details: `Année scolaire définie comme actuelle` })
    revalidatePath('/admin/terms')
    return { success: true }
}

export async function deleteAcademicYear(yearId: string) {
    const ctx = await getActionContext()
    if (!ctx) return { error: 'Non authentifié' }
    const { schoolId } = ctx
    const db = createAdminClient()

    const { data: year } = await db
        .from('academic_years')
        .select('is_current')
        .eq('id', yearId)
        .eq('school_id', schoolId)
        .single()

    if (year?.is_current) {
        return { error: "Impossible de supprimer l'année en cours. Définissez une autre année comme active d'abord." }
    }

    const { error } = await db
        .from('academic_years')
        .delete()
        .eq('id', yearId)
        .eq('school_id', schoolId)

    if (error) return { error: error.message }

    logActivity({ actorId: ctx.userId, schoolId, action: 'delete_academic_year', entityType: 'academic_year', entityId: yearId, details: `Année scolaire supprimée (id: ${yearId})` })
    revalidatePath('/admin/terms')
    return { success: true }
}

// ─── Terms ─────────────────────────────────────────────────────────────────────

export async function setCurrentTerm(termId: string) {
    const ctx = await getActionContext()
    if (!ctx) return { error: 'Non authentifié' }
    const { schoolId } = ctx
    const db = createAdminClient()

    await db.from('terms').update({ is_current: false }).eq('school_id', schoolId)

    const { error } = await db
        .from('terms')
        .update({ is_current: true })
        .eq('id', termId)
        .eq('school_id', schoolId)

    if (error) return { error: error.message }

    revalidatePath('/admin/terms')
    return { success: true }
}

export type TermUpdateInput = {
    label_fr?:      string
    label_ar?:      string
    start_date?:    string
    end_date?:      string
    conseil_date?:  string | null
    bulletin_date?: string | null
}

function pickTermUpdatePayload(data: TermUpdateInput): Record<string, string | null> {
    const out: Record<string, string | null> = {}
    if (data.label_fr !== undefined)      out.label_fr = data.label_fr
    if (data.label_ar !== undefined)      out.label_ar = data.label_ar
    if (data.start_date !== undefined)    out.start_date = data.start_date
    if (data.end_date !== undefined)      out.end_date = data.end_date
    if (data.conseil_date !== undefined)  out.conseil_date = data.conseil_date
    if (data.bulletin_date !== undefined) out.bulletin_date = data.bulletin_date
    return out
}

export async function updateTerm(id: string, data: TermUpdateInput) {
    const ctx = await getActionContext()
    if (!ctx) return { error: 'Non authentifié' }
    const { schoolId } = ctx
    const db = createAdminClient()

    const payload = pickTermUpdatePayload(data)
    if (Object.keys(payload).length === 0) {
        return { error: 'Aucun champ à mettre à jour' }
    }

    const { error } = await db
        .from('terms')
        .update(payload)
        .eq('id', id)
        .eq('school_id', schoolId)

    if (error) return { error: error.message }

    revalidatePath('/admin/terms')
    return { success: true }
}

export async function closeTerm(currentTermId: string, nextTermId?: string) {
    const ctx = await getActionContext()
    if (!ctx) return { error: 'Non authentifié' }
    const { schoolId } = ctx
    const db = createAdminClient()

    await db.from('terms').update({ is_current: false }).eq('school_id', schoolId)

    if (nextTermId) {
        const { error } = await db
            .from('terms')
            .update({ is_current: true })
            .eq('id', nextTermId)
            .eq('school_id', schoolId)
        if (error) return { error: error.message }
    }

    revalidatePath('/admin/terms')
    return { success: true }
}

export async function deleteTerm(id: string) {
    const ctx = await getActionContext()
    if (!ctx) return { error: 'Non authentifié' }
    const { schoolId } = ctx
    const db = createAdminClient()

    const { data: term } = await db
        .from('terms')
        .select('is_current')
        .eq('id', id)
        .eq('school_id', schoolId)
        .single()

    if (term?.is_current) {
        return { error: "Impossible de supprimer le trimestre actuel. Définissez un autre trimestre comme actuel d'abord." }
    }

    const { error } = await db
        .from('terms')
        .delete()
        .eq('id', id)
        .eq('school_id', schoolId)

    if (error) return { error: error.message }

    revalidatePath('/admin/terms')
    return { success: true }
}
